name = "checkapis"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 20, period = 60 }

